export const links = [
    {
        "id": 5708171,
        "title": "Pomogą Tomaszowi Komendzie pozbyć się &quot;tatuaży&quot; więziennych. Za darmo",
        "description": "Po ostatnim, wstrząsającym wywiadzie z Komendą, w którym przyznał, że marzy o usunięciu śladów tuszu do tatuażu (&quot;zrobili z mojej skóry brudnopis w więzieniu&quot;), odezwała się do niego klinika, która zrobi to za darmo. RiGCz.",
        "tags": "#kultura #rozrywka #polska #film #ciekawostki #komenda",
        "source_url": "https://www.wykop.pl/link/partnerredirect/5708171/",
        "vote_count": 133,
        "bury_count": 23,
        "comments_count": 38,
        "related_count": 0,
        "date": "2020-09-22 08:27:08",
        "author": {
            "login": "WirtualnaPolska",
            "color": 2001,
            "avatar": "https://www.wykop.pl/cdn/c3397992/WirtualnaPolska_9qjYNOIj98,q150.jpg"
        },
        "preview": "https://www.wykop.pl/cdn/c3397993/link_1600755877yzNXO11dABsgY7mT4tgKIX,w104h74.jpg",
        "plus18": false,
        "status": "promoted",
        "can_vote": true,
        "is_hot": false
    },
    {
        "id": 5708019,
        "title": "Portland, Seattle i Nowy Jork zostały ogłoszone miastami anarchistycznymi",
        "description": "Przez prokuratora generalnego USA Williama Barra. Bezpośrednimi konskekwencjami tego ruchu będzie utrata dotacji federalnych.",
        "tags": "#swiat #usa #protest #blacklivesmatter #prawo #bekazlewactwa",
        "source_url": "https://www.dailywire.com/news/breaking-ag-barr-to-officially-designate-3-u-s-cities-as-anarchist-jurisdictions-report-says",
        "vote_count": 119,
        "bury_count": 9,
        "comments_count": 6,
        "related_count": 0,
        "date": "2020-09-22 00:25:20",
        "author": {
            "login": "tenex",
            "color": 2,
            "avatar": "https://www.wykop.pl/cdn/c3397992/avatar_def,q150.png"
        },
        "preview": "https://www.wykop.pl/cdn/c3397993/link_1600726870iVGiiS3cfaQM0FH5zCD2Zg,w104h74.jpg",
        "plus18": false,
        "status": "promoted",
        "can_vote": true,
        "is_hot": false
    },
    {
        "id": 5707371,
        "title": "Pojedynek taneczny pomiędzy amerykańskimi a koreańskimi Marines",
        "description": "Coś na poprawę humoru,biorąc pod uwagę to co się ostatnio dzieje na świecie.",
        "tags": "#swiat #usa #korea #taniec #ciekawostki #wojsko",
        "source_url": "http://www.youtube.com/watch?v=J8KfxgTH1Us",
        "vote_count": 154,
        "bury_count": 25,
        "comments_count": 17,
        "related_count": 0,
        "date": "2020-09-21 15:34:21",
        "author": {
            "login": "Arstotzkaball",
            "color": 1,
            "sex": "male",
            "avatar": "https://www.wykop.pl/cdn/c3397992/Arstotzkaball_EiwElRA9Tt,q150.jpg"
        },
        "preview": "https://www.wykop.pl/cdn/c3397993/link_16006952658OjRBVus3Rqbqw5OiyC0lh,w104h74.jpg",
        "plus18": false,
        "status": "promoted",
        "can_vote": true,
        "is_hot": false
    },
    {
        "id": 5707029,
        "title": "34 letni Mercedes G-Class i jego testy w terenie - Terenwizja",
        "description": "34 letni Mercedes G w terenie, czy warto pakować się w takiego klasyka, jak sobie radzi w trudnym terenie? Zapraszam na do oglądania",
        "tags": "#zainteresowania #offroad #4x4 #samochody #motoryzacja #terenwizja",
        "source_url": "http://www.youtube.com/watch?v=f63c_mD3bKk",
        "vote_count": 156,
        "bury_count": 7,
        "comments_count": 47,
        "related_count": 0,
        "date": "2020-09-21 12:37:25",
        "author": {
            "login": "Tonari_Totoro",
            "color": 2,
            "sex": "male",
            "avatar": "https://www.wykop.pl/cdn/c3397992/Tonari_Totoro_4YaIfSzhch,q150.jpg"
        },
        "preview": "https://www.wykop.pl/cdn/c3397993/link_16006846824i0fMLFNcxIUYzHcmALoqd,w104h74.jpg",
        "plus18": false,
        "status": "promoted",
        "can_vote": true,
        "is_hot": false
    },
    {
        "id": 5708293,
        "title": "Co myśleli o Polakach Rosjanie w czasach Rzeczypospolitej Obojga Narodów",
        "description": "Rzeczpospolita z Wielkim Księstwem Moskiewskim, a później z cesarstwem rosyjskim na przestrzeni 3 ostatnich stuleci jej istnienia głównie utrzymywała wrogie stosunki. Państwo moskiewskie z racji parcia na zachód i jednoczenia ziem ruskich było największym zagrożeniem dla Rzeczypospolitej...",
        "tags": "#historykon #historia #nauka #ciekawostki #gruparatowaniapoziomu #polska",
        "source_url": "http://www.youtube.com/watch?v=RVc31nV5Nvo",
        "vote_count": 108,
        "bury_count": 3,
        "comments_count": 24,
        "related_count": 0,
        "date": "2020-09-22 10:00:11",
        "author": {
            "login": "sropo",
            "color": 2,
            "avatar": "https://www.wykop.pl/cdn/c3397992/sropo_9YHIThDNsO,q150.jpg"
        },
        "preview": "https://www.wykop.pl/cdn/c3397993/link_1600761613nWNc3P6HQpDDmqrYBlkGBN,w104h74.jpg",
        "plus18": false,
        "status": "promoted",
        "can_vote": true,
        "is_hot": false
    },
    {
        "id": 5707581,
        "title": "Pościg w Afryce Południowej",
        "description": "Pościg za przestępcami w Afryce.",
        "tags": "#policja #poscig #przestepcy #zlodzieje #przestepczosc",
        "source_url": "https://streamable.com/s192tc",
        "vote_count": 180,
        "bury_count": 0,
        "comments_count": 43,
        "related_count": 1,
        "date": "2020-09-21 18:01:44",
        "author": {
            "login": "starnak",
            "color": 2,
            "sex": "male",
            "avatar": "https://www.wykop.pl/cdn/c3397992/starnak_r6fbn4iNln,q150.jpg"
        },
        "preview": "https://www.wykop.pl/cdn/c3397993/link_1600704105WzUOJLU3TDmo7BvfyuWUC2,w104h74.jpg",
        "plus18": true,
        "status": "promoted",
        "can_vote": true,
        "is_hot": false
    },
    {
        "id": 5708015,
        "title": "Panika wśród sławnych i bogatych - nazwiska pasażerów Lolita Express wyjdą...",
        "description": "Serwis dailymail.co.uk podaje, że spodziewać się możemy ujawnienia nazwisk wszystkich pasażerów samolotu Jeffrey'a Epsteina. Potencjalna lista miała jeszcze przed publikacją wywołać panikę w środowisku bogatych i sławnych przyjaciół miliardera.",
        "tags": "#swiat #usa #pedofilia #hollywood #polityka #film",
        "source_url": "https://kobieta.onet.pl/jeffrey-epstein-nazwiska-osob-ktore-lataly-z-nim-samolotem-lolita-express/56xvzgx",
        "vote_count": 207,
        "bury_count": 4,
        "comments_count": 43,
        "related_count": 0,
        "date": "2020-09-22 00:17:53",
        "author": {
            "login": "Pyza56",
            "color": 1,
            "sex": "female",
            "avatar": "https://www.wykop.pl/cdn/c3397992/Pyza56_LMCQUuOgjO,q150.jpg"
        },
        "preview": "https://www.wykop.pl/cdn/c3397993/link_1600726500F4VU1Y1gy8Cn3vmtY0nfnf,w104h74.jpg",
        "plus18": false,
        "status": "promoted",
        "can_vote": true,
        "is_hot": false
    },
    {
        "id": 5707933,
        "title": "Jak wygląda świat, gdy zbliżamy się do prędkości światła?",
        "description": "Symulacja, wraz z obszernym komentarzem, na przykładzie świata, w którym c=2m/s.",
        "tags": "#nauka #technologie #ciekawostki #kosmos",
        "source_url": "https://youtu.be/udqihUBGuZ8",
        "vote_count": 172,
        "bury_count": 8,
        "comments_count": 36,
        "related_count": 1,
        "date": "2020-09-21 22:13:40",
        "author": {
            "login": "ex3v",
            "color": 2,
            "sex": "male",
            "avatar": "https://www.wykop.pl/cdn/c3397992/ex3v_7d2b0e9384,q150.jpg"
        },
        "preview": "https://www.wykop.pl/cdn/c3397993/link_1600719220hli31NU8Ddw8E5epmKzweK,w104h74.jpg",
        "plus18": false,
        "status": "promoted",
        "can_vote": true,
        "is_hot": false,
        "app": "Android"
    },
    {
        "id": 5707553,
        "title": "Udawanie potrącenia level expert",
        "description": "Coś jednak się nie udało",
        "tags": "#polska #polskiedrogi #samochody #motoryzacja #stopcham #heheszki",
        "source_url": "http://www.youtube.com/watch?v=jVWcnoi1vLo",
        "vote_count": 538,
        "bury_count": 92,
        "comments_count": 85,
        "related_count": 1,
        "date": "2020-09-21 17:39:16",
        "author": {
            "login": "mirkacz",
            "color": 1,
            "avatar": "https://www.wykop.pl/cdn/c3397992/mirkacz_csVG2kDSwp,q150.jpg"
        },
        "preview": "https://www.wykop.pl/cdn/c3397993/link_1600702760fpOxOEAN3HMLhbi34T1WWU,w104h74.jpg",
        "plus18": false,
        "status": "promoted",
        "can_vote": true,
        "is_hot": false
    },
    {
        "id": 5707959,
        "title": "Proponował seks 14-latce. Nieoficjalnie: to znany muzyk disco polo",
        "description": "Policjanci zatrzymali 27-letniego mężczyznę, który za pośrednictwem internetu korespondował z 14-letnią dziewczynką. Składał jej propozycje seksualne i wysyłał zdjęcia swoich narządów płciowych. W jego mieszkaniu znaleziono broń oraz narkotyki. Według nieoficjalnych informacji zatrzymany...",
        "tags": "#polska #discopolo #muzyka #kryminalne",
        "source_url": "https://www.polsatnews.pl/wiadomosc/2020-09-21/proponowal-seks-14-latce-nieoficjalnie-to-znany-muzyk-disco-polo/",
        "vote_count": 291,
        "bury_count": 8,
        "comments_count": 233,
        "related_count": 3,
        "date": "2020-09-21 22:54:26",
        "author": {
            "login": "polsatnews_pl",
            "color": 2001,
            "avatar": "https://www.wykop.pl/cdn/c3397992/polsatnews_pl_LH6sQnfq2E,q150.jpg"
        },
        "preview": "https://www.wykop.pl/cdn/c3397993/link_1600721607BRDb7To4BYvf7TMqV37eNU,w104h74.jpg",
        "plus18": false,
        "status": "promoted",
        "can_vote": true,
        "is_hot": false
    },
    {
        "id": 5707261,
        "title": "Ludzie związani z Ordo Iuris chcą od seniorów pieniędzy za zbawienie",
        "description": "&quot;Matka Boża zapowiedziała (...) zbawienie każdemu, kto będzie rozpowszechniał nabożeństwo&quot;. Dlatego proszę wpłacić pieniądze na nasze konto. Tak można streścić list, który do seniorów w całej Polsce rozsyła Stowarzyszenie Kultury Chrześcijańskiej im. księdza Piotra Skargi.",
        "tags": "#polska #bekazkatoli #neuropa #patologiazewsi #heheszki",
        "source_url": "https://aszdziennik.pl/130677,ludzie-zwiazani-z-ordo-iuris-chca-od-seniorow-pieniedzy-za-zbawienie-wtf",
        "vote_count": 460,
        "bury_count": 107,
        "comments_count": 48,
        "related_count": 3,
        "date": "2020-09-21 14:49:18",
        "author": {
            "login": "Kempes",
            "color": 2,
            "sex": "male",
            "avatar": "https://www.wykop.pl/cdn/c3397992/Kempes_UqiucNlj7L,q150.jpg"
        },
        "preview": "https://www.wykop.pl/cdn/c3397993/link_1600692508thPTN6K7CFbtECroCOnljj,w104h74.jpg",
        "plus18": false,
        "status": "promoted",
        "can_vote": true,
        "is_hot": false
    },
    {
        "id": 5708067,
        "title": "Polacy przeciwko bezkarności urzędników w walce z Covid-19",
        "description": "Ponad 61 procent pytanych źle ocenia ustawę o &quot;bezkarności urzędników&quot;, która pozwala na złamanie przepisów w związku z walką z pandemią koronawirusa. Takie wyniki przynosi sondaż przeprowadzony przez United Surveys dla RMF FM i &quot;Dziennika Gazety Prawnej&quot;.",
        "tags": "#polska #covid19 #polityka #prawo #koronawirus",
        "source_url": "https://www.wykop.pl/link/partnerredirect/5708067/",
        "vote_count": 291,
        "bury_count": 3,
        "comments_count": 22,
        "related_count": 0,
        "date": "2020-09-22 06:57:27",
        "author": {
            "login": "DzonySiara",
            "color": 2,
            "sex": "male",
            "avatar": "https://www.wykop.pl/cdn/c3397992/DzonySiara_6e6Nf6zzp4,q150.jpg"
        },
        "preview": "https://www.wykop.pl/cdn/c3397993/link_1600750602EUzhqOnwC24MkXeSRu0iyb,w104h74.jpg",
        "plus18": false,
        "status": "promoted",
        "can_vote": true,
        "is_hot": false
    },
    {
        "id": 5707499,
        "title": "Sośnierz: Zwierzęta nie powinny mieć praw, ponieważ nie płacą podatków",
        "description": "Dobromir Sośnierz (Konfederacja) wypowiedział się na temat praw zwierząt. Sośnierz mówi m.in. że zwierzęta nie mają praw, ponieważ nie płacą podatków. Czy przypadkiem Konfederacja nie postuluje maksymalnego ograniczenia podatków? Czy oznacza to analogicznie ograniczenie także praw człowieka?",
        "tags": "#polska #polityka #konfederacja #heheszki #bekazprawakow",
        "source_url": "http://polityczek.pl/uncategorised/13721-sosnierz-zwierzeta-nie-powinny-miec-praw-bo-nie-placa-podatkow",
        "vote_count": 389,
        "bury_count": 109,
        "comments_count": 221,
        "related_count": 3,
        "date": "2020-09-21 17:01:03",
        "author": {
            "login": "mcdevillo",
            "color": 1,
            "avatar": "https://www.wykop.pl/cdn/c3397992/avatar_def,q150.png"
        },
        "preview": "https://www.wykop.pl/cdn/c3397993/link_1600700310gnldcF5W1y4l2RDiodM3jL,w104h74.jpg",
        "plus18": false,
        "status": "promoted",
        "can_vote": true,
        "is_hot": false
    },
    {
        "id": 5708201,
        "title": "#ZTwoichPodatków - Niskie Składki",
        "description": "Minister Finansów ogłosił konkurs #ZTwoichPodatków, który polega na nakręceniu filmu, który będzie pokazywał na co idą nasze podatki. \r\nStowarzyszenie Niskie Składki zrobiło. \r\nWykonanie pół na pół, tak w sam raz na poziomie ministerstwa.",
        "tags": "#polska #ZTwoichPodatków #niskieskladki #wolnyrynek #gospodarka #bekazpisu",
        "source_url": "https://www.facebook.com/niskieskladki/videos/558805264865665/?_fb_noscript=1",
        "vote_count": 994,
        "bury_count": 13,
        "comments_count": 87,
        "related_count": 3,
        "date": "2020-09-22 08:56:33",
        "author": {
            "login": "Tumurochir",
            "color": 1,
            "sex": "male",
            "avatar": "https://www.wykop.pl/cdn/c3397992/Tumurochir_0dxGHGGrwE,q150.jpg"
        },
        "preview": "https://www.wykop.pl/cdn/c3397993/link_1600757644VyRdM0Jv2FGQP1hAww0r3u,w104h74.jpg",
        "plus18": false,
        "status": "promoted",
        "can_vote": true,
        "is_hot": true
    },
    {
        "id": 5707825,
        "title": "Hodowli norek zakazali. Kiedy ochrony doczekają się kurczaki?",
        "description": "Każdego roku 300 mln samców kurczaków jest zabijanych w brutalny sposób. \r\nPolski udział w tym procederze to 40 mln kurcząt poddawanych maceracji – tj. mieleniu żywcem.",
        "tags": "#polska #europa #zwierzeta #kurczak",
        "source_url": "https://centaurus.org.pl/petycja-mielenie_kurczat-nie-dla-mielnia-kurczat/#wiecej",
        "vote_count": 490,
        "bury_count": 103,
        "comments_count": 292,
        "related_count": 2,
        "date": "2020-09-21 20:56:38",
        "author": {
            "login": "galanonym",
            "color": 1,
            "sex": "male",
            "avatar": "https://www.wykop.pl/cdn/c3397992/avatar_def,q150.png"
        },
        "preview": "https://www.wykop.pl/cdn/c3397993/link_16007138780OxJMRuFHgU58prRoUYgKp,w104h74.jpg",
        "plus18": false,
        "status": "promoted",
        "can_vote": true,
        "is_hot": false
    },
    {
        "id": 5707551,
        "title": "Jutro dzień bez samochodu. Aktywiści zastanawiają się, gdzie zaparkują.",
        "description": "Na demonstrację pt. Dzień bez samochodu trzeba przyjechać samochodem. Przecież inaczej się nie da.",
        "tags": "#motoryzacja",
        "source_url": "https://spidersweb.pl/autoblog/dzien-bez-samochodu-2020-parkowanie/",
        "vote_count": 415,
        "bury_count": 27,
        "comments_count": 124,
        "related_count": 2,
        "date": "2020-09-21 17:39:08",
        "author": {
            "login": "Ksebki",
            "color": 2,
            "sex": "male",
            "avatar": "https://www.wykop.pl/cdn/c3397992/avatar_def,q150.png"
        },
        "preview": "https://www.wykop.pl/cdn/c3397993/link_1600702704Y03JGuAZGw3Wu6uOi0HveU,w104h74.jpg",
        "plus18": false,
        "status": "promoted",
        "can_vote": true,
        "is_hot": false
    },
    {
        "id": 5708191,
        "title": "LAVA CAKE - niesamowity deser z płynną czekoladą w 15 minut",
        "description": "Już kilku osobom to obiecałem, więc przed Wami  - lava cake, jeden z ulubionych deserów mojego różowego. Wydaje się skomplikowany, ale jest bardzo prosty w przygotowaniu. \r\n\r\nW powiązanych przepis w wersji pisanej :)",
        "tags": "#kuchniamg78",
        "source_url": "http://www.youtube.com/watch?v=9hiST0KX7yo",
        "vote_count": 632,
        "bury_count": 27,
        "comments_count": 89,
        "related_count": 1,
        "date": "2020-09-22 08:45:29",
        "author": {
            "login": "MG78",
            "color": 2,
            "sex": "male",
            "avatar": "https://www.wykop.pl/cdn/c3397992/MG78_KdLFQL79Q1,q150.jpg"
        },
        "preview": "https://www.wykop.pl/cdn/c3397993/link_1600757130rDJsRKOCgyWm05VIZUw0ok,w104h74.jpg",
        "plus18": false,
        "status": "promoted",
        "can_vote": true,
        "is_hot": true
    },
    {
        "id": 5707915,
        "title": "Egipt: Odkryto 27 sarkofagów sprzed 2,5 tys. lat",
        "description": "Archeolodzy odkryli w Egipcie 27 drewnianych sarkofagów pochodzących sprzed 2,5 tys. lat. Wydobyto je na terenie starożytnej nekropolii w Sakkarze, gdzie znajduje się również piramida Dżesera - prawdopodobnie najstarsza w Egipcie.",
        "tags": "#swiat #ciekawostki #egipt #archeologia #historia #ciekawostkihistoryczne",
        "source_url": "https://www.wykop.pl/link/partnerredirect/5707915/",
        "vote_count": 275,
        "bury_count": 1,
        "comments_count": 27,
        "related_count": 1,
        "date": "2020-09-21 22:04:29",
        "author": {
            "login": "Popke523",
            "color": 2,
            "avatar": "https://www.wykop.pl/cdn/c3397992/avatar_def,q150.png"
        },
        "preview": "https://www.wykop.pl/cdn/c3397993/link_1600718621NeLXWxC2qLQI5AcMOf9FAf,w104h74.jpg",
        "plus18": false,
        "status": "promoted",
        "can_vote": true,
        "is_hot": false
    },
    {
        "id": 5708055,
        "title": "Rafał Ziemkiewicz usunięty z TVP Info po krytyce ustawy antyfutrzarskiej",
        "description": "Publicysta Rafał Ziemkiewicz rozważa zawieszenie współpracy z Telewizji Polskiej i TV Republika. W publicznej telewizji przestał się już pojawiać i nie wiadomo, kiedy wróci. - Nie ma mnie w grafiku, to dżentelmeńska umowa - mówi w rozmowie z portalem Wirtualnemedia.pl.",
        "tags": "#polska #kultura #rozrywka",
        "source_url": "https://www.wykop.pl/link/partnerredirect/5708055/",
        "vote_count": 671,
        "bury_count": 21,
        "comments_count": 188,
        "related_count": 3,
        "date": "2020-09-22 06:27:23",
        "author": {
            "login": "Wirtualnemedia_pl",
            "color": 2001,
            "avatar": "https://www.wykop.pl/cdn/c3397992/avatar_def,q150.png"
        },
        "preview": "https://www.wykop.pl/cdn/c3397993/link_16007488166nDWUDXU5uominpsIkprPi,w104h74.jpg",
        "plus18": false,
        "status": "promoted",
        "can_vote": true,
        "is_hot": false
    },
    {
        "id": 5707421,
        "title": "Włochy: Obywatele w referendum poparli redukcję liczby parlamentarzystów",
        "description": "Ponad 60 proc. Włochów poparło w zakończonym w poniedziałek referendum konstytucyjnym ustawę o redukcji liczby parlamentarzystów. Ustawa przewiduje od następnej kadencji zmniejszenie liczby deputowanych z 630 do 400, a senatorów z 315 do 200.",
        "tags": "#wlochy #pieniadze #rzad #prawo #parlament",
        "source_url": "https://www.wnp.pl/rynki-zagraniczne/wlochy-obywatele-w-referendum-poparli-redukcje-liczby-parlamentarzystow-exit-polls,419895.html",
        "vote_count": 495,
        "bury_count": 1,
        "comments_count": 93,
        "related_count": 2,
        "date": "2020-09-21 16:04:43",
        "author": {
            "login": "ssakul",
            "color": 2,
            "avatar": "https://www.wykop.pl/cdn/c3397992/avatar_def,q150.png"
        },
        "preview": "https://www.wykop.pl/cdn/c3397993/link_1600696782t9Ip9x4PpEk09TNrrLYcMQ,w104h74.jpg",
        "plus18": false,
        "status": "promoted",
        "can_vote": true,
        "is_hot": false
    },
    {
        "id": 5707613,
        "title": "Oszuści sprzedają kawałek papieru za 2,5k złotych",
        "description": "Korzystając z dużego popytu i niedostępności kart na rynku, cwaniaki próbują ugrać na nieuwadze innych ludzi",
        "tags": "#polska #nvidia #3080 #oszukujo",
        "source_url": "https://allegro.pl/oferta/nvidia-rtx-3080-founders-paper-edition-9722354955?fbclid=IwAR0q0poF95BdSGD8NHJVFbiYa-Q45RlbMLCIPyWJFlwATTTvQxxh--h0iw4",
        "vote_count": 438,
        "bury_count": 20,
        "comments_count": 193,
        "related_count": 1,
        "date": "2020-09-21 18:08:50",
        "author": {
            "login": "Stamp",
            "color": 1,
            "sex": "male",
            "avatar": "https://www.wykop.pl/cdn/c3397992/Stamp_uLMrq3cT09,q150.jpg"
        },
        "preview": "https://www.wykop.pl/cdn/c3397993/link_1600704390xCeV9iXq2XwkUqD8CuiYvx,w104h74.jpg",
        "plus18": false,
        "status": "promoted",
        "can_vote": true,
        "is_hot": false
    },
    {
        "id": 5707795,
        "title": "„Ukraiński Homar” z amunicją kasetową. Tymczasem Polska czeka na gotowca z USA",
        "description": "Siły zbrojne Ukrainy przeprowadziły strzelanie z wykorzystaniem 300 mm pocisku Wilcha-R. Jest to kierowany pocisk o donośności ponad 70 km z głowicą kasetową, rozwijany w ramach programu systemu rakietowego Wilcha. Test na poligonie w rejonie Chersonia przeprowadzono w ramach ćwiczeń",
        "tags": "#ukraina #wojsko #militaria #technologia #ciekawostkizewschodu #donbaswar",
        "source_url": "https://www.defence24.pl/ukrainski-homar-z-amunicja-kasetowa",
        "vote_count": 301,
        "bury_count": 6,
        "comments_count": 97,
        "related_count": 2,
        "date": "2020-09-21 20:26:10",
        "author": {
            "login": "jakubbaumann",
            "color": 1,
            "sex": "male",
            "avatar": "https://www.wykop.pl/cdn/c3397992/jakubbaumann_hLYu5Uj3ZW,q150.jpg"
        },
        "preview": "https://www.wykop.pl/cdn/c3397993/link_1600712601YtNe04CtPuCBS4L7G8AKuu,w104h74.jpg",
        "plus18": false,
        "status": "promoted",
        "can_vote": true,
        "is_hot": false
    },
    {
        "id": 5707493,
        "title": "Burmistrz nie zwołuje rady osiedla przez COVID, ale organizuje imprezy masowe.",
        "description": "5 miesięcy temu minęła czteroletnia kadencja rady osiedla Stare Miasto. Burmistrz nie chce zwołać zebrania, ponieważ nie można organizować wydarzeń liczących więcej niż 150 osób. Tymczasem w ciągu miesiąca miasto organizowało co najmniej trzy imprezy, w których udział brało kilkuset ludzi.",
        "tags": "#polska #koronawirus #urzedasstory #patologiazewsi #patologiazmiasta #afera",
        "source_url": "https://uwielbiampandy.blogspot.com/2020/09/hipokryzja-burmistrza-ecznej-nie-zwouje.html",
        "vote_count": 412,
        "bury_count": 2,
        "comments_count": 19,
        "related_count": 1,
        "date": "2020-09-21 16:53:16",
        "author": {
            "login": "Cukrzyk2000",
            "color": 2,
            "sex": "male",
            "avatar": "https://www.wykop.pl/cdn/c3397992/Cukrzyk2000_RAmOh9mpkz,q150.jpg"
        },
        "preview": "https://www.wykop.pl/cdn/c3397993/link_1600699433fj3qIzNDIQlkbWm0hArqmR,w104h74.jpg",
        "plus18": false,
        "status": "promoted",
        "can_vote": true,
        "is_hot": false
    },
    {
        "id": 5707855,
        "title": "Deputowani z Ukrainy chcą oficjalnie świętować rocznicę sojuszu z Hitlerem",
        "description": "Deputowana nacjonalistycznej partii Swoboda wniosła projekt ustawy o dniu „Aktu odrodzenia państwa ukraińskiego”. Akt ten stworzyli w 1941 roku banderowcy z OUN-B, a jego 3. pkt mówił o ścisłej współpracy nowego państwa z hitlerowskimi Niemcami. Projekt poparli również przedstawiciele innych partii.",
        "tags": "#ukraina #banderowcy #ciekawostkizewschodu #bekazprawakow #bekaznarodowcow #antykapitalizm",
        "source_url": "https://strajk.eu/deputowani-ukrainskiej-rady-najwyzszej-chca-oficjalnie-swietowac-rocznice-sojuszu-z-hitlerem/",
        "vote_count": 420,
        "bury_count": 17,
        "comments_count": 79,
        "related_count": 0,
        "date": "2020-09-21 21:17:53",
        "author": {
            "login": "rodnorev",
            "color": 1,
            "sex": "male",
            "avatar": "https://www.wykop.pl/cdn/c3397992/rodnorev_DpMKM99QCm,q150.jpg"
        },
        "preview": "https://www.wykop.pl/cdn/c3397993/link_1600715232oyn9vEnbWwG428IlSADotg,w104h74.jpg",
        "plus18": false,
        "status": "promoted",
        "can_vote": true,
        "is_hot": false
    },
    {
        "id": 5707237,
        "title": "Czy USA zalegalizuje marihuanę na szczeblu federalnym? Dziś głosowanie.",
        "description": "Izba Reprezentantów USA kontrolowana przez Demokratów już dzisiaj zagłosuje w sprawie legalizacji marihuany na szczeblu federalnym. Ustawa wprowadzona przez przedstawiciela demokratów – Jerry’ego Nadlera, jeśli zostanie przegłosowana, to usunie marihuanę z federalnej listy substancji...",
        "tags": "#swiat #usa #marihuana #wykopjointclub #ciekawostki #prawo",
        "source_url": "https://faktykonopne.pl/czy-usa-zalegalizuje-marihuane-na-szczeblu-federalnym-juz-dzis-historyczne-glosowanie/",
        "vote_count": 485,
        "bury_count": 7,
        "comments_count": 63,
        "related_count": 2,
        "date": "2020-09-21 14:35:21",
        "author": {
            "login": "damccio",
            "color": 2,
            "sex": "male",
            "avatar": "https://www.wykop.pl/cdn/c3397992/damccio_khPhje3WCV,q150.jpg"
        },
        "preview": "https://www.wykop.pl/cdn/c3397993/link_1600691351V4T1HhsWPNMFTtRxusDN8E,w104h74.jpg",
        "plus18": false,
        "status": "promoted",
        "can_vote": true,
        "is_hot": false
    },
    {
        "id": 5707939,
        "title": "Osobnik rozjuszony niczym zwierzę atakuję samotną kobietę w metrze",
        "description": "Agresor uderzył kobietę ponad dwadzieścia razy. Ofiara prosiła aby przestał, ten natomiast powiedział ze przeprasza i gdy ofiara odsłoniła twarz dalej kontynuował atak. Kobieta doznała wstrząsu, złamanego żebra oraz licznych siniaków. Tego samego dnia zaatakował kolejne dwie osoby.",
        "tags": "#swiat #miami #usa #wydarzenia",
        "source_url": "https://www.dailymail.co.uk/news/article-8756035/Moment-man-25-viciously-assaults-lone-female-rider-29-unprovoked-attack-Miami-metro.html",
        "vote_count": 544,
        "bury_count": 17,
        "comments_count": 100,
        "related_count": 2,
        "date": "2020-09-21 22:14:48",
        "author": {
            "login": "Gentleman_Adrian",
            "color": 2,
            "sex": "male",
            "avatar": "https://www.wykop.pl/cdn/c3397992/Gentleman_Adrian_5MPt1j2d9A,q150.jpg"
        },
        "preview": "https://www.wykop.pl/cdn/c3397993/link_1600717509ulk1IUg0nJeLzWIGLvWI4b,w104h74.jpg",
        "plus18": true,
        "status": "promoted",
        "can_vote": true,
        "is_hot": false
    },
    {
        "id": 5707899,
        "title": "Wojskowe ZOO, czyli prawdziwie śmiercionośne zwierzęta [galeria]",
        "description": "Proponujemy wycieczkę po wirtualnym wojskowym ZOO. Jest to placówka w 100% bezpieczna, o ile pozostaniecie Państwo na wyznaczonych ścieżkach i nie będziecie wychodzić poza ogrodzenia. No i proszę pamiętać o pułapkach termicznych oraz zasłonie dymnej.",
        "tags": "#nauka #liganauki #gruparatowaniapoziomu #qualitycontent #historia #swiatnauki",
        "source_url": "https://tytus.edu.pl/2020/09/21/wojskowe-zoo-czyli-prawdziwie-smiercionosne-zwierzeta-galeria/",
        "vote_count": 209,
        "bury_count": 3,
        "comments_count": 26,
        "related_count": 2,
        "date": "2020-09-21 21:51:39",
        "author": {
            "login": "Czajna_Seczen",
            "color": 2,
            "sex": "male",
            "avatar": "https://www.wykop.pl/cdn/c3397992/Czajna_Seczen_yOpb0DS2SX,q150.jpg"
        },
        "preview": "https://www.wykop.pl/cdn/c3397993/link_1600717847hbdAeJx4JOHrJjv9BLQ5fz,w104h74.jpg",
        "plus18": false,
        "status": "promoted",
        "can_vote": true,
        "is_hot": false
    },
    {
        "id": 5707391,
        "title": "Tajemnicza twierdza na skraju chińskiej pustyni",
        "description": "Miasto sprzed 4300 lat o którym nie wspominają żadne źródła historyczne, z wielką piramidą, zaawansowanymi fortyfikacjami i tajemniczymi rzeźbami zdobionymi jadeitem importowanym tysiące kilometrów. Przy budowie jego murów złożono w ofierze 80 młodych dziewcząt.",
        "tags": "#swiat #historia #archeologia #gruparatowaniapoziomu #chiny #ciekawostkihistoryczne",
        "source_url": "https://www.nationalgeographic.com/history/2020/08/mysterious-carvings-evidence-human-sacrifice-uncovered-ancient-city-china/",
        "vote_count": 314,
        "bury_count": 0,
        "comments_count": 92,
        "related_count": 0,
        "date": "2020-09-21 15:55:28",
        "author": {
            "login": "kaspil",
            "color": 1,
            "sex": "female",
            "avatar": "https://www.wykop.pl/cdn/c3397992/kaspil_cQnY31Tuoe,q150.jpg"
        },
        "preview": "https://www.wykop.pl/cdn/c3397993/link_1600696042JIT7NmSkmqXMWyVXFtZxyJ,w104h74.jpg",
        "plus18": false,
        "status": "promoted",
        "can_vote": true,
        "is_hot": false
    },
    {
        "id": 5707733,
        "title": "Antifa VS pies!",
        "description": "Hey wot the fok( ͡° ͜ʖ ͡°)",
        "tags": "#usa #antifa #blm #heheszki #pies",
        "source_url": "https://streamable.com/5y616w",
        "vote_count": 547,
        "bury_count": 57,
        "comments_count": 70,
        "related_count": 0,
        "date": "2020-09-21 19:47:57",
        "author": {
            "login": "wojna",
            "color": 2,
            "sex": "male",
            "avatar": "https://www.wykop.pl/cdn/c3397992/wojna_LH4IWHTCyC,q150.jpg"
        },
        "preview": "https://www.wykop.pl/cdn/c3397993/link_1600710479uPPB9sLiThCShLPuEnAMTZ,w104h74.jpg",
        "plus18": false,
        "status": "promoted",
        "can_vote": true,
        "is_hot": false
    },
    {
        "id": 5707997,
        "title": "YouTube cenzuruje wywiad na kanale Moniki Jaruzelskiej za &quot;mowę nienawiści&quot;",
        "description": "Po 3 miesiącach od premiery odcinka z Rafałem Ziemkiewiczem, pomimo wcześniejszego przesłania do YT do akceptacji –  odcinek został usunięty. Kuriozalne jest również to, że YT do dziś zarabiał na reklamach.",
        "tags": "#polska #cenzura #youtube #polityka #afera",
        "source_url": "https://www.facebook.com/MonikaJaruzelska/posts/3192216687499270?_fb_noscript=1",
        "vote_count": 580,
        "bury_count": 25,
        "comments_count": 95,
        "related_count": 1,
        "date": "2020-09-21 23:25:50",
        "author": {
            "login": "zjadlbymbanana",
            "color": 1,
            "sex": "male",
            "avatar": "https://www.wykop.pl/cdn/c3397992/zjadlbymbanana_KvYyDKOQXk,q150.jpg"
        },
        "preview": "https://www.wykop.pl/cdn/c3397993/link_1600723225diHlNC7Wo6yEnKFjn2w97z,w104h74.jpg",
        "plus18": false,
        "status": "promoted",
        "can_vote": true,
        "is_hot": false
    },
    {
        "id": 5706977,
        "title": "Nietypowe skrzyżowanie torów kolejowych",
        "description": "miejsce akcji: gdzieś w Australii",
        "tags": "#kolej #ciekawostki #zainteresowania #pociagi",
        "source_url": "https://youtu.be/-UcbflOnffg",
        "vote_count": 354,
        "bury_count": 6,
        "comments_count": 56,
        "related_count": 0,
        "date": "2020-09-21 12:05:14",
        "author": {
            "login": "Antidotum119",
            "color": 1,
            "sex": "female",
            "avatar": "https://www.wykop.pl/cdn/c3397992/Antidotum119_aVuxaFZcPY,q150.jpg"
        },
        "preview": "https://www.wykop.pl/cdn/c3397993/link_1600682714nyPh6aNa9hJ1imvRpAapBU,w104h74.jpg",
        "plus18": false,
        "status": "promoted",
        "can_vote": true,
        "is_hot": false,
        "app": "Android"
    },
    {
        "id": 5706433,
        "title": "W Detroit aresztowano faceta który przeskoczył samochodem most zwodzony",
        "description": "W trakcie lądowania wybuchły wszystkie opony. Najprawdopodobniej odpowie za zniszczenie szlabanu i jazdę pod wpływem substancji odurzających. Miniaturka nie przedstawia opisywanego zdarzenia.",
        "tags": "#swiat #usa #samochody #ciekawostki",
        "source_url": "https://www.coasttocoastam.com/article/video-detroit-driver-arrested-after-successfully-jumping-over-drawbridge",
        "vote_count": 418,
        "bury_count": 11,
        "comments_count": 67,
        "related_count": 2,
        "date": "2020-09-21 00:59:59",
        "author": {
            "login": "kaspil",
            "color": 1,
            "sex": "female",
            "avatar": "https://www.wykop.pl/cdn/c3397992/kaspil_cQnY31Tuoe,q150.jpg"
        },
        "preview": "https://www.wykop.pl/cdn/c3397993/link_16006424988LA8PZpupT3TwrwdPy0OI0,w104h74.jpg",
        "plus18": false,
        "status": "promoted",
        "can_vote": true,
        "is_hot": false
    },
    {
        "id": 5707671,
        "title": "Właściciel Lidla i Kauflandu najbogatszym Niemcem",
        "description": "80-letni Dieter Schwarz, właściciel sieci spożywczych Lidl i Kaufland, jest najbogatszym Niemcem - wynika z opublikowanego przez &quot;Welt am Sonntag&quot; rankingu. Mimo kryzysu bogaci stają się coraz bogatsi - zauważa dziennik.",
        "tags": "#europa #niemcy #pieniadze",
        "source_url": "https://gospodarka.dziennik.pl/news/artykuly/7828776,lidl-kaufland-wlasciciel-najbogatszy-niemiec.html",
        "vote_count": 521,
        "bury_count": 4,
        "comments_count": 219,
        "related_count": 4,
        "date": "2020-09-21 18:52:48",
        "author": {
            "login": "rybak_fischermann",
            "color": 2,
            "sex": "male",
            "avatar": "https://www.wykop.pl/cdn/c3397992/rybak_fischermann_JEK0HTz92c,q150.jpg"
        },
        "preview": "https://www.wykop.pl/cdn/c3397993/link_1600707133B38SsasE7izrZquAqoWMah,w104h74.jpg",
        "plus18": false,
        "status": "promoted",
        "can_vote": true,
        "is_hot": false
    },
    {
        "id": 5706467,
        "title": "To wtedy po raz pierwszy zawiał &quot;boski wiatr&quot;. Mongolska inwazja na Japonię.",
        "description": "Przywołując historię Kraju Kwitnącej Wiśni, często myślimy o militarnych podbojach i tradycji samurajów. Jednak przed wiekami potężne cesarstwo stanęło przed zagrożeniem, które mogło zniszczyć nie tylko jego przeszłość, ale i przyszłość... Mongolska inwazja była wyjątkowo mrocznym...",
        "tags": "#polska #europa #ps4 #historia #japonia #ciekawostki",
        "source_url": "https://www.wykop.pl/link/partnerredirect/5706467/",
        "vote_count": 236,
        "bury_count": 11,
        "comments_count": 45,
        "related_count": 1,
        "date": "2020-09-21 06:53:06",
        "author": {
            "login": "CiekawostkiHistoryczne",
            "color": 2001,
            "avatar": "https://www.wykop.pl/cdn/c3397992/CiekawostkiHistoryczne_bDcbFY5LYr,q150.jpg"
        },
        "preview": "https://www.wykop.pl/cdn/c3397993/link_160066389875lwQSFEF0xEOpv71ZyeCS,w104h74.jpg",
        "plus18": false,
        "status": "promoted",
        "can_vote": true,
        "is_hot": false
    },
    {
        "id": 5706893,
        "title": "Pijana matka pojechała na zakupy z 2-latkiem. Upuściła chłopca podczas...",
        "description": "Pijana matka z 2-letnim synkiem przyjechała samochodem do marketu w Teresinie na Mazowszu. Podczas wsiadania do auta upuściła dziecko. Kobietę zatrzymał zaniepokojony jej zachowaniem mężczyzna. Nie pozwolił jej odjechać i wezwał policję.",
        "tags": "#polska #madki #dzieci #patologiazmiasta",
        "source_url": "https://www.wykop.pl/link/partnerredirect/5706893/",
        "vote_count": 312,
        "bury_count": 7,
        "comments_count": 53,
        "related_count": 0,
        "date": "2020-09-21 11:20:42",
        "author": {
            "login": "ptakdodo",
            "color": 1,
            "sex": "male",
            "avatar": "https://www.wykop.pl/cdn/c3397992/ptakdodo_AVR9UbuuoL,q150.jpg"
        },
        "preview": "https://www.wykop.pl/cdn/c3397993/link_16006799079WyegDwd7VChGxKQYgDMev,w104h74.jpg",
        "plus18": false,
        "status": "promoted",
        "can_vote": true,
        "is_hot": false
    },
    {
        "id": 5706853,
        "title": "Lista &quot;dokonań&quot; PiSu. Krótko.",
        "description": "Jesteśmy nawet nie po roku drugiej kadencji rządów PiS. Jeśli tak to będzie szło, pod koniec możemy już naszego pięknego kraju nie poznać. Jeśli ktoś głosując na PiS miał nadzieję, że wybiera rozsądną,przyjazną ludziom, konserwatywną ekipę, która będzie stanowić dobrą odmianę– to srodze się pomylił.",
        "tags": "#polska #polityka #bekazprawakow #konfederacja #prawo #bekazpisu",
        "source_url": "https://www.se.pl/wiadomosci/polityka/lukasz-warzecha-bezkompromisowo-o-prawie-i-sprawiedliwosci-lista-dokonan-aa-9f3a-tLMr-RACC.html?fbclid=IwAR0NXVW3YSaXulaYcYIwXEECGX4FvEsUSnCSQctXrx0u04Q5Vzx7IpNW244",
        "vote_count": 444,
        "bury_count": 28,
        "comments_count": 55,
        "related_count": 0,
        "date": "2020-09-21 10:54:10",
        "author": {
            "login": "Rastuff",
            "color": 2,
            "sex": "male",
            "avatar": "https://www.wykop.pl/cdn/c3397992/Rastuff_wRIyQ4sddy,q150.jpg"
        },
        "preview": "https://www.wykop.pl/cdn/c3397993/link_1600678069IZ8YwYhvfCUTj4hkJh1IqF,w104h74.jpg",
        "plus18": false,
        "status": "promoted",
        "can_vote": true,
        "is_hot": false
    },
    {
        "id": 5707655,
        "title": "Od 6 lat Polacy są mistrzami świata. Historia triumfu siatkarzy na MŚ 2014",
        "description": "Trener-żółtodziób. Drużyna pozbawiona wielkiej gwiazdy. Kapitan tylko cudem postawiony na nogi na najważniejsze mecze. To nie miało prawa się udać. A jednak. Sześć lat temu, 21 września 2014 roku, Polacy zostali mistrzami świata w siatkówce. Tytuł ten zachowali także po kolejnym turnieju.",
        "tags": "#polska #sport #siatkowka #reprezentacja",
        "source_url": "https://www.wykop.pl/link/partnerredirect/5707655/",
        "vote_count": 454,
        "bury_count": 8,
        "comments_count": 77,
        "related_count": 2,
        "date": "2020-09-21 18:33:26",
        "author": {
            "login": "WPSportoweFakty",
            "color": 2,
            "avatar": "https://www.wykop.pl/cdn/c3397992/avatar_def,q150.png"
        },
        "preview": "https://www.wykop.pl/cdn/c3397993/link_16007057222B3RZ7QpKJEkzeGTBLENJq,w104h74.jpg",
        "plus18": false,
        "status": "promoted",
        "can_vote": true,
        "is_hot": false
    },
    {
        "id": 5707023,
        "title": "Nowy trend ma TikToku - palenie książek J.K. Rowling ze względu na jej poglądy",
        "description": "Yup, &quot;byli fani książek&quot; palą książki o Harry'm Potterze ze względu na poglądy autorki na transpłciowość. Treść nowych książek też znalazła się pod ostrzałem.",
        "tags": "#kultura #harrypotter #bekazlewactwa #4konserwy",
        "source_url": "https://www.newsweek.com/jk-rowling-books-burned-tiktok-transgender-issues-1532330",
        "vote_count": 711,
        "bury_count": 36,
        "comments_count": 270,
        "related_count": 4,
        "date": "2020-09-21 12:30:52",
        "author": {
            "login": "Czesiowcy",
            "color": 2,
            "sex": "male",
            "avatar": "https://www.wykop.pl/cdn/c3397992/Czesiowcy_Rt8IFfMsqn,q150.jpg"
        },
        "preview": "https://www.wykop.pl/cdn/c3397993/link_1600683920uhqMTkCBNw87OEmSxr5ko4,w104h74.jpg",
        "plus18": false,
        "status": "promoted",
        "can_vote": true,
        "is_hot": false
    },
    {
        "id": 5707003,
        "title": "Górnicy rozpoczęli strajk. Nie wyjechali na powierzchnię po porannej...",
        "description": "Górnicy z kopalni Bielszowice w Rudzie Śląskiej nie wyjechali na powierzchnię po porannj szychcie. Strajki zaplanowane są tez w innych kopalniach",
        "tags": "#polska #zainteresowania #ekonomia #gornictwo",
        "source_url": "https://www.eska.pl/slaskie/gornicy-groza-strajkiem-dzisiaj-mija-ultimatum-jakie-zwiazkowcy-dali-premierowi-aa-MrFz-c9wQ-x5ix.html",
        "vote_count": 357,
        "bury_count": 11,
        "comments_count": 168,
        "related_count": 0,
        "date": "2020-09-21 12:20:35",
        "author": {
            "login": "arekadio94",
            "color": 2,
            "sex": "male",
            "avatar": "https://www.wykop.pl/cdn/c3397992/avatar_def,q150.png"
        },
        "preview": "https://www.wykop.pl/cdn/c3397993/link_1600683546AY2tEo4IPyl3yjyHteQJVW,w104h74.jpg",
        "plus18": false,
        "status": "promoted",
        "can_vote": true,
        "is_hot": false
    },
    {
        "id": 5707775,
        "title": "W ringu wygrał, ale po walce werdykt zmieniono. Polak na wojnie z Niemcami",
        "description": "Rafał Jackiewicz poszedł na wojnę po sierpniowej walce w Niemczech i zmianie werdyktu, która kosztowała go zwycięstwo. Jego prawnicy już wysłali pismo do niemieckiego wydziału boksu zawodowego. Niewykluczone, że sprawa skończy się w sądzie.",
        "tags": "#polska #boks #sport #sportywalki #sztukiwalki",
        "source_url": "https://www.wykop.pl/link/partnerredirect/5707775/",
        "vote_count": 633,
        "bury_count": 12,
        "comments_count": 64,
        "related_count": 0,
        "date": "2020-09-21 20:16:41",
        "author": {
            "login": "WPSportoweFakty",
            "color": 2,
            "avatar": "https://www.wykop.pl/cdn/c3397992/avatar_def,q150.png"
        },
        "preview": "https://www.wykop.pl/cdn/c3397993/link_1600712031BltWaWgzn2KrLlgK5637Kw,w104h74.jpg",
        "plus18": false,
        "status": "promoted",
        "can_vote": true,
        "is_hot": false
    },
    {
        "id": 5706779,
        "title": "Andrzej Duda skłania się do zawetowania &quot;Piątki dla zwierząt&quot;. Chce zmian ustawy",
        "description": "Prezydent Andrzej Duda skłania się do zawetowania &quot;Piątki dla zwierząt&quot;. Nie zrobi tego, jeżeli w ustawie zostaną wprowadzone daleko idące zmiany. Prezydent chce m.in. usunięcia z ustawy ograniczeń dotyczących uboju rytualnego.",
        "tags": "#polska #polityka #wydarzenia #zwierzeta #bekazpisu #neuropa",
        "source_url": "https://www.wykop.pl/link/partnerredirect/5706779/",
        "vote_count": 261,
        "bury_count": 7,
        "comments_count": 100,
        "related_count": 1,
        "date": "2020-09-21 10:19:37",
        "author": {
            "login": "Szewczenko",
            "color": 2,
            "sex": "male",
            "avatar": "https://www.wykop.pl/cdn/c3397992/avatar_def,q150.png"
        },
        "preview": "https://www.wykop.pl/cdn/c3397993/link_16006762979QP8Ix9jlUwbtTv9SHhzL5,w104h74.jpg",
        "plus18": false,
        "status": "promoted",
        "can_vote": true,
        "is_hot": false
    },
    {
        "id": 5706929,
        "title": "USA: liczba samobójstw wśród dzieci oraz młodych dorosłych wzrosła o 57%",
        "description": "W ciągu dekady liczba samobójstw popełniana przez osoby w wieku 10-24 wzrosła o 57% i nadal ma tendencje wzrostowe. Dane udostępnione przez National Center for Health Statistics pokazują, że wskaźnik samobójstw w 2018 r. wyniósł 14 na 100 tys. mieszkańców, gdzie w 2007 r. wynosił 7 na 100 tys.",
        "tags": "#swiat #usa #samobojstwo #depresja #nauka #psychologia",
        "source_url": "https://www.wykop.pl/link/partnerredirect/5706929/",
        "vote_count": 392,
        "bury_count": 9,
        "comments_count": 126,
        "related_count": 1,
        "date": "2020-09-21 11:40:31",
        "author": {
            "login": "Anywherepl",
            "color": 2001,
            "avatar": "https://www.wykop.pl/cdn/c3397992/Anywherepl_rjK4h0PLC3,q150.jpg"
        },
        "preview": "https://www.wykop.pl/cdn/c3397993/link_1600681105o5mDbDxIZWv0eea3DzeTQg,w104h74.jpg",
        "plus18": false,
        "status": "promoted",
        "can_vote": true,
        "is_hot": false
    },
    {
        "id": 5707031,
        "title": "Bezemisyjny samolot Airbusa  zasilany wodorem",
        "description": "Airbus ujawnił trzy koncepcje bezemisyjnego samolotu komercyjnego, który mógłby wejść do służby do 2035 r.",
        "tags": "#europa #lotnictwo #samoloty #technologia #ciekawostki #aircraftboners",
        "source_url": "https://www.rynek-lotniczy.pl/mobile/airbus-przedstawia-nowy-samolot-koncepcyjny-o-zerowej-emisji-9608.html",
        "vote_count": 326,
        "bury_count": 6,
        "comments_count": 135,
        "related_count": 1,
        "date": "2020-09-21 12:37:31",
        "author": {
            "login": "Ag90",
            "color": 1,
            "sex": "female",
            "avatar": "https://www.wykop.pl/cdn/c3397992/Ag90_ogbO4GrH3B,q150.jpg"
        },
        "preview": "https://www.wykop.pl/cdn/c3397993/link_1600683763BAYnSKA81XQ6XHlpNejMCt,w104h74.jpg",
        "plus18": false,
        "status": "promoted",
        "can_vote": true,
        "is_hot": false
    },
    {
        "id": 5707245,
        "title": "Dlaczego Niemcy są bogaci?",
        "description": "Z czego wynikał powojenny cud gospodarczy Niemiec? Na zdjęciu Konrad Adenauer były Kanclerz Niemiec",
        "tags": "#niemcy #europa #ciekawostki #ciekawostkihistoryczne #gruparatowaniapoziomu #iiwojnaswiatowa",
        "source_url": "https://www.facebook.com/photo.php?fbid=10224390750937618&amp;amp%3Bamp%3Bamp%3Bset=a.1560862022736&amp;amp%3Bamp%3Bamp%3Btype=3&amp;amp%3Bamp%3Bamp%3Btheater&amp;amp%3Bamp%3Bamp%3B_fb_noscript=1&amp;amp%3Bamp%3B_fb_noscript=1&amp;amp%3B_fb_noscript=",
        "vote_count": 444,
        "bury_count": 13,
        "comments_count": 232,
        "related_count": 2,
        "date": "2020-09-21 14:37:15",
        "author": {
            "login": "DziennikCodzienny",
            "color": 1,
            "sex": "male",
            "avatar": "https://www.wykop.pl/cdn/c3397992/DziennikCodzienny_y1oxaHCCIk,q150.jpg"
        },
        "preview": "https://www.wykop.pl/cdn/c3397993/link_1600691663Jx4sBJPxEaYn00JHyMVx6S,w104h74.jpg",
        "plus18": false,
        "status": "promoted",
        "can_vote": true,
        "is_hot": false
    },
    {
        "id": 5707773,
        "title": "Skrót propagandowych wiadomości TVP: 21 września 2020",
        "description": "Trzaskowski nie dba o kina, wyburza je dla firm, martwi się tylko o muzykę. &quot;Małe Partie&quot; AWSizują zjednoczoną prawicę. PL mosty i drogi są NAJLEPSZE W EUROPIE. PL konie i Janów Podlaski jest w pyte.",
        "tags": "#tvpis #tvpiscodzienny #polska #warszawa #bekazpisu #gruparatowaniapoziomu",
        "source_url": "https://www.wykop.pl/wpis/52267939",
        "vote_count": 385,
        "bury_count": 43,
        "comments_count": 16,
        "related_count": 0,
        "date": "2020-09-21 20:15:44",
        "author": {
            "login": "jaxonxst",
            "color": 2,
            "sex": "male",
            "avatar": "https://www.wykop.pl/cdn/c3397992/jaxonxst_m9plTn0WKF,q150.jpg"
        },
        "plus18": false,
        "status": "promoted",
        "can_vote": true,
        "is_hot": false,
        "app": "Android"
    },
    {
        "id": 5706535,
        "title": "&quot;Barierołamacz&quot; dokonał niemożliwego. Zawstydził turystów nad Morskim Okiem",
        "description": "Artur Świercz od urodzenia jest osobą z niepełnosprawnością. Ma przepuklinę oponowo-rdzeniową. Choroba nie odbiera mu jednak spełniania swoich marzeń. Jak mało kto pokazuje, że – mimo wielu przeszkód –",
        "tags": "#polska #morskieoko #niepelnosprawni #zdrowie #gory #tatry",
        "source_url": "https://www.wykop.pl/link/partnerredirect/5706535/",
        "vote_count": 360,
        "bury_count": 101,
        "comments_count": 99,
        "related_count": 0,
        "date": "2020-09-21 08:08:25",
        "author": {
            "login": "WirtualnaPolska",
            "color": 2001,
            "avatar": "https://www.wykop.pl/cdn/c3397992/WirtualnaPolska_9qjYNOIj98,q150.jpg"
        },
        "preview": "https://www.wykop.pl/cdn/c3397993/link_1600668428kcGRP6p3VUC2xFIra7RZll,w104h74.jpg",
        "plus18": false,
        "status": "promoted",
        "can_vote": true,
        "is_hot": false
    },
    {
        "id": 5707383,
        "title": "budowa wycieczkowca LPG [timelapse]",
        "description": "składanie klocków dla dużych chłopców",
        "tags": "#ciekawostki #technologia #inzynieria",
        "source_url": "http://www.youtube.com/watch?v=GkiW5GsFVbs",
        "vote_count": 361,
        "bury_count": 0,
        "comments_count": 90,
        "related_count": 1,
        "date": "2020-09-21 15:45:09",
        "author": {
            "login": "TiempoSanto",
            "color": 2,
            "sex": "male",
            "avatar": "https://www.wykop.pl/cdn/c3397992/TiempoSanto_HxrGtsdSZb,q150.jpg"
        },
        "preview": "https://www.wykop.pl/cdn/c3397993/link_1600695911M9mWPzuWQOtLhDlWKqO2gi,w104h74.jpg",
        "plus18": false,
        "status": "promoted",
        "can_vote": true,
        "is_hot": false
    },
    {
        "id": 5706769,
        "title": "Pinkas: Wygenerujemy emocjonalne zapotrzebowanie na szczepionkę przeciw...",
        "description": "Konfederacja w mediach społecznościowych zamieściła materiał z zastanawiającą wypowiedzą ministra Jarosława Pikasa. Główny Inspektor Sanitarny mówi w niej m.in. o wygenerowaniu emocjonalnego zapotrzebowania wśród Polaków na szczepionkę przeciw COVID-19. Konfederacja: – Maski opadły?...",
        "tags": "#polska #medycyna #koronawirus #szczepienia #zdrowie #covid19",
        "source_url": "https://naszapolska.pl/2020/09/21/pinkas-wygenerujemy-emocjonalne-zapotrzebowanie-na-szczepionke-przeciw-covid-19/",
        "vote_count": 529,
        "bury_count": 49,
        "comments_count": 103,
        "related_count": 3,
        "date": "2020-09-21 10:11:07",
        "author": {
            "login": "Karol_1070",
            "color": 2,
            "sex": "male",
            "avatar": "https://www.wykop.pl/cdn/c3397992/Karol_1070_JzuhmAwTsf,q150.jpg"
        },
        "preview": "https://www.wykop.pl/cdn/c3397993/link_1600675753BWI864OspIpQRrmV5jTYH4,w104h74.jpg",
        "plus18": false,
        "status": "promoted",
        "can_vote": true,
        "is_hot": false
    },
    {
        "id": 5707691,
        "title": "Departament Sprawiedliwości USA uznał New York, Portland  i Seattle jako...",
        "description": "Strefy przemocy i anarchii. Tym samym odcinając je od funduszy federalnych do czasu przywrócenia w nich porządku.\r\nTL;DR w komenatrzu [Eng]",
        "tags": "#usa #bekazlewactwa #4konserwy #polityka #prawo #nowyjork",
        "source_url": "https://thefederalist.com/2020/09/21/doj-officially-designates-nyc-portland-seattle-as-violent-anarchy-zones/",
        "vote_count": 471,
        "bury_count": 2,
        "comments_count": 48,
        "related_count": 1,
        "date": "2020-09-21 19:04:08",
        "author": {
            "login": "rifraw",
            "color": 2,
            "sex": "male",
            "avatar": "https://www.wykop.pl/cdn/c3397992/rifraw_e7TnDGpIkW,q150.jpg"
        },
        "preview": "https://www.wykop.pl/cdn/c3397993/link_1600705999TutF3khm6xtDo8lJDlXNXN,w104h74.jpg",
        "plus18": false,
        "status": "promoted",
        "can_vote": true,
        "is_hot": false
    },
    {
        "id": 5707227,
        "title": "Bill Murray, amerykański komik i kultowy aktor, kończy 70 lat!",
        "description": "Bill Murray urodził się 21 września 1950 roku, więc ma dziś urodziny. Z tej okazji warto prześledzić jego filmografię, powspominać i poznać tytuły, które warto znać!",
        "tags": "#kultura #rozrywka #ciekawostki #film #kino #swiat",
        "source_url": "https://naekranie.pl/artykuly/bill-murray-konczy-70-lat-wybieramy-najciekawsze-filmy-amerykanskiego-komika",
        "vote_count": 593,
        "bury_count": 15,
        "comments_count": 75,
        "related_count": 3,
        "date": "2020-09-21 14:29:02",
        "author": {
            "login": "m-jarecki",
            "color": 2,
            "sex": "male",
            "avatar": "https://www.wykop.pl/cdn/c3397992/m-jarecki_zrT4XSQ0QK,q150.jpg"
        },
        "preview": "https://www.wykop.pl/cdn/c3397993/link_1600691166Gad5iMAxh0SXBWvlY63woB,w104h74.jpg",
        "plus18": false,
        "status": "promoted",
        "can_vote": true,
        "is_hot": false
    }
]